version: "3.1"
services:
  postgres:
    container_name: postgres-pizza
    image: postgres:latest
    ports:
    - "5435:5432"
    volumes:
    - pg:/data/asset
    env_file:
    - .env

volumes:
  pg: